create database prediktadb;

use prediktadb;

drop table TOURNAMENT;

create table TOURNAMENT(
TOURNAMENT_NAME varchar(50),
TOURNAMENT_COUNTRY varchar(30),
TOURNAMENT_SPORT varchar(30),
PLAYER_OF_THE_SERIES varchar(30)
);

select * from tournament;

ALTER TABLE TOURNAMENT MODIFY TOURNAMENT_NAME char(50);

create table USER_UPDATE(
MATCH_NUMBER int,
MATCH_DATE DATETIME DEFAULT (CURRENT_DATE),
USERNAME varchar(30),
PLAYER_OF_THE_MATCH_1 varchar(30),
PLAYER_OF_THE_MATCH_2 varchar(30),
PLAYER_OF_THE_MATCH_3 varchar(30),
WINNING_TEAM varchar(20),
SCORE int
);

drop table SQUADS;

CREATE TABLE SQUADS(
PLAYER_ID int PRIMARY KEY AUTO_INCREMENT, 
PLAYER_NAME VARCHAR(30) , 
TEAM_NAME VARCHAR(30), 
POSITION VARCHAR(20));

select * from SQUADS;

drop table SCHEDULE;

CREATE TABLE SCHEDULE(
MATCH_DATE DATE, 
MATCH_NUMBER INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
FIRST_TEAM VARCHAR(30), 
SECOND_TEAM VARCHAR(30), 
WINNER VARCHAR(20), 
PLAYER_OF_THE_MATCH VARCHAR(30));

select * from Schedule;

